package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;




/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String user;
     private String password;
     private String type;

    public Login() {
    }

    public Login(String user, String password, String type) {
       this.user = user;
       this.password = password;
       this.type = type;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

public Login LoginCheck(String user,String Password)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from Login where user='"+user+"' and password='"+Password+"'");
    Login lst=(Login)query.uniqueResult();
    session.close();
    return lst;
}

public void updateRecord(Login login)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from Login where user='"+login.getUser()+"'");
        System.out.println("from Login where user='"+login.getUser()+"'");

        Login info = (Login)query.uniqueResult();
        info.setPassword(login.getPassword());
        Transaction transaction = session.beginTransaction();
        session.update(info);
        transaction.commit();
        session.close();
    }

public void insertData(Login info)
    {
        Session session = HibeConnect.getSession();
        Transaction transaction = session.beginTransaction();
        session.save(info);
        transaction.commit();
        session.close();
    }


public void deleteRecord(String name)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from Login where user = :name");
        query.setString("name", name);
        Login info = (Login)query.uniqueResult();
        Transaction transaction = session.beginTransaction();
        session.delete(info);
        transaction.commit();
        session.close();
    }
}


