package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA

import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * TbAdmin generated by hbm2java
 */
public class TbAdmin  implements java.io.Serializable {


     private String adminId;
     private String AFristname;
     private String ALastname;
     private String AGender;
     private String ACity;
     private String AEmail;
     private String AContact;
     private String AAddress;

    public TbAdmin() {
    }

	
    public TbAdmin(String adminId) {
        this.adminId = adminId;
    }
    public TbAdmin(String adminId, String AFristname, String ALastname, String AGender, String ACity, String AEmail, String AContact, String AAddress) {
       this.adminId = adminId;
       this.AFristname = AFristname;
       this.ALastname = ALastname;
       this.AGender = AGender;
       this.ACity = ACity;
       this.AEmail = AEmail;
       this.AContact = AContact;
       this.AAddress = AAddress;
    }
   
    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }
    public String getAFristname() {
        return this.AFristname;
    }
    
    public void setAFristname(String AFristname) {
        this.AFristname = AFristname;
    }
    public String getALastname() {
        return this.ALastname;
    }
    
    public void setALastname(String ALastname) {
        this.ALastname = ALastname;
    }
    public String getAGender() {
        return this.AGender;
    }
    
    public void setAGender(String AGender) {
        this.AGender = AGender;
    }
    public String getACity() {
        return this.ACity;
    }
    
    public void setACity(String ACity) {
        this.ACity = ACity;
    }
    public String getAEmail() {
        return this.AEmail;
    }
    
    public void setAEmail(String AEmail) {
        this.AEmail = AEmail;
    }
    public String getAContact() {
        return this.AContact;
    }
    
    public void setAContact(String AContact) {
        this.AContact = AContact;
    }
    public String getAAddress() {
        return this.AAddress;
    }
    
    public void setAAddress(String AAddress) {
        this.AAddress = AAddress;
    }


public TbAdmin adminPro(String User)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbAdmin where adminId='"+User+"'");
    TbAdmin tb=(TbAdmin)query.uniqueResult();
    session.close();
    return tb;
}

public List all()
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbAdmin");
    List li=query.list();
    session.close();
    return li;

    }

public String myString()
    {
    return adminId;
    }

}


