package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * TbCourses generated by hbm2java
 */
public class TbCourses  implements java.io.Serializable {


     private String CId;
     private String CDid;
     private String CName;
     private Date CStartdate;
      private String CAbb;

    public String getCAbb() {
        return CAbb;
    }

    public void setCAbb(String CAbb) {
        this.CAbb = CAbb;
    }

    public TbCourses() {
    }

	
    public TbCourses(String CId) {
        this.CId = CId;
    }
    public TbCourses(String CId, String CAbb,String CDid, String CName, Date CStartdate) {
       this.CId = CId;
       this.CDid = CDid;
       this.CName = CName;
       this.CStartdate = CStartdate;
    }
   
    public String getCId() {
        return this.CId;
    }
    
    public void setCId(String CId) {
        this.CId = CId;
    }
    public String getCDid() {
        return this.CDid;
    }
    
    public void setCDid(String CDid) {
        this.CDid = CDid;
    }
    public String getCName() {
        return this.CName;
    }
    
    public void setCName(String CName) {
        this.CName = CName;
    }
    public Date getCStartdate() {
        return this.CStartdate;
    }
    
    public void setCStartdate(Date CStartdate) {
        this.CStartdate = CStartdate;
    }


public List fetch(String act)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbCourses where CDid='"+act+"'");
    List li=query.list();
    System.out.println(li.size());
    session.close();
    return li;
    }

public TbCourses fetchAll(String act)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbCourses where CId='"+act+"'");
    TbCourses li=(TbCourses)query.uniqueResult();
    System.out.println(li.CName);
    session.close();
    return li;
    }

public void insertData(TbCourses info)
    {
        Session session = HibeConnect.getSession();
        Transaction transaction = session.beginTransaction();
        System.out.println(info.getCAbb());
        info.setCAbb(info.getCAbb());
        session.save(info);
        transaction.commit();
        session.close();
    }

public void updateRecord(String CId, String CAbb, String CName)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbCourses where CId ='"+CId+"'");
        //query.setString("name", CId);
        System.out.print("from TbCourses where CId ='"+CId+"'");
        TbCourses info = (TbCourses)query.uniqueResult();
        System.out.println("Info issssssssssss"+info);
        info.setCAbb(CAbb);
        info.setCName(CName);
       // info.setDTimetable(DTimeTable);
        Transaction transaction = session.beginTransaction();
        session.update(info);
        transaction.commit();
        session.close();
    }


public void deleteRecord(String name)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbCourses where CId = :name");
        query.setString("name", name);
        TbCourses info = (TbCourses)query.uniqueResult();
        Transaction transaction = session.beginTransaction();
        session.delete(info);
        transaction.commit();
        session.close();
    }

public List fetchcourse()
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbCourses");
    List li=query.list();
    System.out.println(li.size());
    session.close();
    return li;
    }

public String toString()
    {
return CId;
}

}


