package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA

import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;




/**
 * TbDepartment generated by hbm2java
 */
public class TbDepartment  implements java.io.Serializable {


     private String DId;
     private String DName;
     private String DHod;
     private String DTimetable;

    public TbDepartment() {
    }

	
    public TbDepartment(String DId) {
        this.DId = DId;
    }
    public TbDepartment(String DId, String DName, String DHod, String DTimetable) {
       this.DId = DId;
       this.DName = DName;
       this.DHod = DHod;
       this.DTimetable = DTimetable;
    }
   
    public String getDId() {
        return this.DId;
    }
    
    public void setDId(String DId) {
        this.DId = DId;
    }
    public String getDName() {
        return this.DName;
    }
    
    public void setDName(String DName) {
        this.DName = DName;
    }
    public String getDHod() {
        return this.DHod;
    }
    
    public void setDHod(String DHod) {
        this.DHod = DHod;
    }
    public String getDTimetable() {
        return this.DTimetable;
    }
    
    public void setDTimetable(String DTimetable) {
        this.DTimetable = DTimetable;
    }

        public List fetchDept(String s)
    {
        Session session=HibeConnect.getSession();
        Query query=session.createQuery("from TbDepartment where DId='"+s+"'");
        System.out.println("from TbDepartment where DId='"+s+"'");
        List li=query.list();
        session.close();
        return li;
        }

        public void insertData(TbDepartment info)
    {
        Session session = HibeConnect.getSession();
        Transaction transaction = session.beginTransaction();
        session.save(info);
        transaction.commit();
        session.close();
    }
         public List fetch()
    {
        Session session=HibeConnect.getSession();
        Query query=session.createQuery("from TbDepartment");
        
        List li=query.list();
        System.out.print(li);
        session.close();
        return li;
        }

           public TbDepartment fetchup(String s)
    {
        Session session=HibeConnect.getSession();
        Query query=session.createQuery("from TbDepartment where DId='"+s+"'");
        System.out.println("from TbDepartment where DId='"+s+"'");
        TbDepartment li=(TbDepartment)query.uniqueResult();
        session.close();
        return li;
        }


 public void updateRecord(String DId, String DName, String DHod)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbDepartment where DId = :name");
        query.setString("name", DId);
        TbDepartment info = (TbDepartment)query.uniqueResult();
        info.setDName(DName);
        info.setDHod(DHod);
       // info.setDTimetable(DTimeTable);
        Transaction transaction = session.beginTransaction();
        session.update(info);
        transaction.commit();
        session.close();
    }

 public void update(String DId,String d)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbDepartment where DId = '"+DId+"'");
        System.out.print("from TbDepartment where DId = '"+DId+"' and DTimetable='"+DTimetable+"'");
        //query.setString("name", DId);
        System.out.println("vale is..........."+d);
        TbDepartment info = (TbDepartment)query.uniqueResult();
        info.setDTimetable(d);
       // info.setDHod(DHod);
       // info.setDTimetable(DTimeTable);
        Transaction transaction = session.beginTransaction();
        session.update(info);
        transaction.commit();
        session.close();
    }


public void deleteRecord(String name)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbDepartment where DId = :name");
        query.setString("name", name);
        TbDepartment info = (TbDepartment)query.uniqueResult();
        Transaction transaction = session.beginTransaction();
        session.delete(info);
        transaction.commit();
        session.close();
    }

public String toString()
    {
return DId;
}

}


