package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * TbFaculty generated by hbm2java
 */
public class TbFaculty  implements java.io.Serializable {


     private String FId;
     private String FFirstname;
     private String FLastname;
     private String FDid;
     private String FGender;
     private Date FDob;
     private String FAddress;
     private String FCity;
     private String FState;
     private String FEmail;
     private String FQualification;
     private Integer FExperience;
     private String FDesignation;
     private Date FJoindate;
     private String FImage;

    public TbFaculty() {
    }

	
    public TbFaculty(String FId) {
        this.FId = FId;
    }
    public TbFaculty(String FId, String FFirstname, String FLastname, String FDid, String FGender, Date FDob, String FAddress, String FCity, String FState, String FEmail, String FQualification, Integer FExperience, String FDesignation, Date FJoindate, String FImage) {
       this.FId = FId;
       this.FFirstname = FFirstname;
       this.FLastname = FLastname;
       this.FDid = FDid;
       this.FGender = FGender;
       this.FDob = FDob;
       this.FAddress = FAddress;
       this.FCity = FCity;
       this.FState = FState;
       this.FEmail = FEmail;
       this.FQualification = FQualification;
       this.FExperience = FExperience;
       this.FDesignation = FDesignation;
       this.FJoindate = FJoindate;
       this.FImage = FImage;
    }
   
    public String getFId() {
        return this.FId;
    }
    
    public void setFId(String FId) {
        this.FId = FId;
    }
    public String getFFirstname() {
        return this.FFirstname;
    }
    
    public void setFFirstname(String FFirstname) {
        this.FFirstname = FFirstname;
    }
    public String getFLastname() {
        return this.FLastname;
    }
    
    public void setFLastname(String FLastname) {
        this.FLastname = FLastname;
    }
    public String getFDid() {
        return this.FDid;
    }
    
    public void setFDid(String FDid) {
        this.FDid = FDid;
    }
    public String getFGender() {
        return this.FGender;
    }
    
    public void setFGender(String FGender) {
        this.FGender = FGender;
    }
    public Date getFDob() {
        return this.FDob;
    }
    
    public void setFDob(Date FDob) {
        this.FDob = FDob;
    }
    public String getFAddress() {
        return this.FAddress;
    }
    
    public void setFAddress(String FAddress) {
        this.FAddress = FAddress;
    }
    public String getFCity() {
        return this.FCity;
    }
    
    public void setFCity(String FCity) {
        this.FCity = FCity;
    }
    public String getFState() {
        return this.FState;
    }
    
    public void setFState(String FState) {
        this.FState = FState;
    }
    public String getFEmail() {
        return this.FEmail;
    }
    
    public void setFEmail(String FEmail) {
        this.FEmail = FEmail;
    }
    public String getFQualification() {
        return this.FQualification;
    }
    
    public void setFQualification(String FQualification) {
        this.FQualification = FQualification;
    }
    public Integer getFExperience() {
        return this.FExperience;
    }
    
    public void setFExperience(Integer FExperience) {
        this.FExperience = FExperience;
    }
    public String getFDesignation() {
        return this.FDesignation;
    }
    
    public void setFDesignation(String FDesignation) {
        this.FDesignation = FDesignation;
    }
    public Date getFJoindate() {
        return this.FJoindate;
    }
    
    public void setFJoindate(Date FJoindate) {
        this.FJoindate = FJoindate;
    }
    public String getFImage() {
        return this.FImage;
    }
    
    public void setFImage(String FImage) {
        this.FImage = FImage;
    }


public List fetch(String act)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbFaculty where FDid='"+act+"'");
    List li=query.list();
    System.out.println(li.size());
    session.close();
    return li;
    }

public void insertData(TbFaculty info)
    {
        Session session = HibeConnect.getSession();
        Transaction transaction = session.beginTransaction();
        session.save(info);
        transaction.commit();
        session.close();
    }



public List fetchAll()
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbFaculty");
    List li=query.list();
    System.out.println(li.size());
    session.close();
    return li;
    }


public void updateRecord(String FId,String FDId,String FFirstname,String FLastname,Date FJoinDate,String FDesignation)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbFaculty where FId = :name");
        query.setString("name", FId);
        System.out.println(FId);
        TbFaculty info = (TbFaculty)query.uniqueResult();
        info.setFFirstname(FFirstname);
        info.setFLastname(FLastname);
        info.setFJoindate(FJoinDate);
        info.setFDesignation(FDesignation);
       // info.setDTimetable(DTimeTable);
        Transaction transaction = session.beginTransaction();
        session.update(info);
        transaction.commit();
        session.close();
    }


public void deleteRecord(String name)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbFaculty where FId = :name");
        query.setString("name", name);
        TbFaculty info = (TbFaculty)query.uniqueResult();
        Transaction transaction = session.beginTransaction();
        session.delete(info);
        transaction.commit();
        session.close();
    }


public TbFaculty fetcha(String s)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbFaculty where FId='"+s+"'");
    TbFaculty li=(TbFaculty)query.uniqueResult();
    //System.out.println(li.size());
    session.close();
    return li;
    }

public void updateFaculty(TbFaculty faculty)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbFaculty where FId='"+faculty.getFId()+"'");
        System.out.println("from TbFaculty where FId='"+faculty.getFId()+"'");

        TbFaculty info = (TbFaculty)query.uniqueResult();

        Transaction transaction = session.beginTransaction();

        info.setFAddress(faculty.getFAddress());
        info.setFCity(faculty.getFCity());
        
        info.setFDesignation(faculty.getFDesignation());
        info.setFDob(faculty.getFDob());
        info.setFEmail(faculty.getFEmail());
        info.setFExperience(faculty.getFExperience());
        info.setFFirstname(faculty.getFFirstname());
        info.setFGender(faculty.getFGender());
        info.setFImage(faculty.getFImage());
        info.setFLastname(faculty.getFLastname());
        info.setFQualification(faculty.getFQualification());
        info.setFState(faculty.getFState());
System.out.println(info+"updated");

        session.update(info);
        transaction.commit();
        session.close();
    }

public String myString()
    {
return FId;}
}


