package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TbLogin generated by hbm2java
 */
public class TbLogin  implements java.io.Serializable {


     private BigDecimal LUser;
     private String LPassword;
     private String LType;
     private Date LLastlogin;

    public TbLogin() {
    }

	
    public TbLogin(BigDecimal LUser, String LPassword, String LType) {
        this.LUser = LUser;
        this.LPassword = LPassword;
        this.LType = LType;
    }
    public TbLogin(BigDecimal LUser, String LPassword, String LType, Date LLastlogin) {
       this.LUser = LUser;
       this.LPassword = LPassword;
       this.LType = LType;
       this.LLastlogin = LLastlogin;
    }
   
    public BigDecimal getLUser() {
        return this.LUser;
    }
    
    public void setLUser(BigDecimal LUser) {
        this.LUser = LUser;
    }
    public String getLPassword() {
        return this.LPassword;
    }
    
    public void setLPassword(String LPassword) {
        this.LPassword = LPassword;
    }
    public String getLType() {
        return this.LType;
    }
    
    public void setLType(String LType) {
        this.LType = LType;
    }
    public Date getLLastlogin() {
        return this.LLastlogin;
    }
    
    public void setLLastlogin(Date LLastlogin) {
        this.LLastlogin = LLastlogin;
    }




}


