package com.cms.hib;
// Generated 8 May, 2011 1:24:29 PM by Hibernate Tools 3.2.1.GA


import java.io.File;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * TbStudent generated by hbm2java
 */
public class TbStudent  implements java.io.Serializable {

private String SNationality;

    public String getSNationality() {
        return SNationality;
    }

    public void setSNationality(String SNationality) {
        this.SNationality = SNationality;
    }
     private String SId;
     private String SFirstname;
     private String SLastname;
     private String SFather;
     private String SMother;
     private String SSession;
     private String SClass;
     private String SGender;
     private Date SDob;
     private String SAddress;
     private String SCity;
     private String SState;
     private String SEmail;
     private String SContact;
     private String SImage;
     private String STenth;
     private String STwelth;
     private String SGraduation;

    public TbStudent() {
    }

	
    public TbStudent(String SId) {
        this.SId = SId;
    }
    public TbStudent(String SId, String SFirstname, String SLastname, String SFather, String SMother, String SSession, String SClass, String SGender, Date SDob, String SAddress, String SCity, String SState, String SEmail, String SContact, String SImage, String STenth, String STwelth, String SGraduation) {
       this.SId = SId;
       this.SFirstname = SFirstname;
       this.SLastname = SLastname;
       this.SFather = SFather;
       this.SMother = SMother;
       this.SSession = SSession;
       this.SClass = SClass;
       this.SGender = SGender;
       this.SDob = SDob;
       this.SAddress = SAddress;
       this.SCity = SCity;
       this.SState = SState;
       this.SEmail = SEmail;
       this.SContact = SContact;
       this.SImage = SImage;
       this.STenth = STenth;
       this.STwelth = STwelth;
       this.SGraduation = SGraduation;
    }
    public TbStudent(String SId, String SFirstname, String SLastname, String SFather, String SMother, String SSession, String SClass, String SGender, Date SDob, String SAddress, String SCity, String SState, String SEmail, String SContact, String SImage, String STenth, String STwelth, String SGraduation,String SNationality) {
       this.SId = SId;
       this.SFirstname = SFirstname;
       this.SLastname = SLastname;
       this.SFather = SFather;
       this.SMother = SMother;
       this.SSession = SSession;
       this.SClass = SClass;
       this.SGender = SGender;
       this.SDob = SDob;
       this.SAddress = SAddress;
       this.SCity = SCity;
       this.SState = SState;
       this.SEmail = SEmail;
       this.SContact = SContact;
       this.SImage = SImage;
       this.STenth = STenth;
       this.STwelth = STwelth;
       this.SGraduation = SGraduation;
       this.SNationality=SNationality;
    }
   
    public String getSId() {
        return this.SId;
    }
    
    public void setSId(String SId) {
        this.SId = SId;
    }
    public String getSFirstname() {
        return this.SFirstname;
    }
    
    public void setSFirstname(String SFirstname) {
        this.SFirstname = SFirstname;
    }
    public String getSLastname() {
        return this.SLastname;
    }
    
    public void setSLastname(String SLastname) {
        this.SLastname = SLastname;
    }
    public String getSFather() {
        return this.SFather;
    }
    
    public void setSFather(String SFather) {
        this.SFather = SFather;
    }
    public String getSMother() {
        return this.SMother;
    }
    
    public void setSMother(String SMother) {
        this.SMother = SMother;
    }
    public String getSSession() {
        return this.SSession;
    }
    
    public void setSSession(String SSession) {
        this.SSession = SSession;
    }
    public String getSClass() {
        return this.SClass;
    }
    
    public void setSClass(String SClass) {
        this.SClass = SClass;
    }
    public String getSGender() {
        return this.SGender;
    }
    
    public void setSGender(String SGender) {
        this.SGender = SGender;
    }
    public Date getSDob() {
        return this.SDob;
    }
    
    public void setSDob(Date SDob) {
        this.SDob = SDob;
    }
    public String getSAddress() {
        return this.SAddress;
    }
    
    public void setSAddress(String SAddress) {
        this.SAddress = SAddress;
    }
    public String getSCity() {
        return this.SCity;
    }
    
    public void setSCity(String SCity) {
        this.SCity = SCity;
    }
    public String getSState() {
        return this.SState;
    }
    
    public void setSState(String SState) {
        this.SState = SState;
    }
    public String getSEmail() {
        return this.SEmail;
    }
    
    public void setSEmail(String SEmail) {
        this.SEmail = SEmail;
    }
    public String getSContact() {
        return this.SContact;
    }
    
    public void setSContact(String SContact) {
        this.SContact = SContact;
    }
    public String getSImage() {
        return this.SImage;
    }
    
    public void setSImage(String SImage) {
        this.SImage = SImage;
    }
    public String getSTenth() {
        return this.STenth;
    }
    
    public void setSTenth(String STenth) {
        this.STenth = STenth;
    }
    public String getSTwelth() {
        return this.STwelth;
    }
    
    public void setSTwelth(String STwelth) {
        this.STwelth = STwelth;
    }
    public String getSGraduation() {
        return this.SGraduation;
    }
    
    public void setSGraduation(String SGraduation) {
        this.SGraduation = SGraduation;
    }


public List fetch(String course,String SSession)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbStudent where SClass='"+course+"' and SSession='"+SSession+"'");
    System.out.println("from TbStudent where SClass='"+course+"' and SSession='"+SSession+"'");
    List li=query.list();
    System.out.println(li.size());
    session.close();
    return li;
    }

public void updateRecord(TbStudent stu)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbStudent where SId='"+stu.getSId()+"'");
        System.out.println("from TbStudent where SId='"+stu.getSId()+"'");

        TbStudent info = (TbStudent)query.uniqueResult();

        Transaction transaction = session.beginTransaction();

        info.setSAddress(stu.getSAddress());
        info.setSCity(stu.getSCity());
        info.setSClass(stu.getSClass());
        info.setSContact(stu.getSContact());
        info.setSDob(stu.getSDob());
        info.setSEmail(stu.getSEmail());
        info.setSFather(stu.getSFather());
        info.setSFirstname(stu.getSFirstname());
        info.setSLastname(stu.getSLastname());

        info.setSMother(stu.getSMother());
        info.setSImage(getSImage());
        info.setSState(stu.getSState());
        info.setSNationality(stu.getSNationality());
        info.setSGraduation(stu.getSGraduation());
        info.setSGender(stu.getSGender());
        info.setSTenth(stu.getSTenth());
        info.setSTwelth(stu.getSTwelth());


        session.update(info);
        transaction.commit();
        session.close();
    }


 public void delete(String name)
    {
        Session session = HibeConnect.getSession();
        Query query = session.createQuery("from TbStudent where SId ='"+name+"'");
  
        System.out.print(name);
        TbStudent info = (TbStudent)query.uniqueResult();
        Transaction transaction = session.beginTransaction();
        session.delete(info);
        transaction.commit();
        session.close();
    }

    public void insertData(TbStudent info)
    {
        Session session = HibeConnect.getSession();
        Transaction transaction = session.beginTransaction();
        session.save(info);
        transaction.commit();
        session.close();
    }

    public TbStudent student(String User)
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbStudent where SId='"+User+"'");
    TbStudent tb=(TbStudent)query.uniqueResult();
    session.close();
    return tb;
}

    public List all()
    {
    Session session=HibeConnect.getSession();
    Query query=session.createQuery("from TbStudent");
    List li=query.list();
    session.close();
    return li;

    }

    public String myString()
    {
    return SId;
    }
}


